services:

  server1:
    build: ./docker
    container_name: server1
    hostname: server1
    ports:
      - "2221:22"
    networks:
      - devops-net

  server2:
    build: ./docker
    container_name: server2
    hostname: server2
    ports:
      - "2222:22"
    networks:
      - devops-net

  server3:
    build: ./docker
    container_name: server3
    hostname: server3
    ports:
      - "2223:22"
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge