---
services:

  server1:
    build: ./docker
    container_name: server1
    hostname: server1
    ports:
      - "2221:22"
    networks:
      - devops-net

  server2:
    build: ./docker
    container_name: server2
    hostname: server2
    ports:
      - "2222:22"
    networks:
      - devops-net

  server3:
    build: ./docker
    container_name: server3
    hostname: server3
    ports:
      - "2223:22"
    networks:
      - devops-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml
      
    networks:
      - devops-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - devops-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge
