---
- name: Crear directorio .ssh
  ansible.builtin.file:
    path: /home/devops/.ssh
    state: directory
    owner: devops
    group: devops
    mode: "0700"

- name: Copiar clave pública
  ansible.posix.authorized_key:
    user: devops
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
