---
- name: Actualizar cache apt
  ansible.builtin.apt:
    update_cache: true

- name: Instalar herramientas base
  ansible.builtin.apt:
    name: "{{ packages_common }}"
    state: present

- name: Crear directorio proyectos
  ansible.builtin.file:
    path: /opt/projects
    state: directory
    mode: "0755"

- name: Configurar sudo sin contraseña
  ansible.builtin.copy:
    dest: /etc/sudoers.d/devops
    content: "devops ALL=(ALL) NOPASSWD:ALL"
    mode: "0440"
