---
global:

route:
  receiver: telegram

receivers:
  - name: telegram

    telegram_configs:
      - bot_token: "8477690615:AAHFU8NhfDuZ38kEuskIhcohNdYVKMinBY0"

        chat_id: 7939143373

        message: |
          🚨 Alerta DevOps Lab

          Alerta:
          {{ .GroupLabels.alertname }}

          Estado:
          {{ .Status }}
