---
global:

route:
  receiver: telegram

receivers:
  - name: telegram

    telegram_configs:
      - bot_token: "TOKEN"

        chat_id: Tu_id

        message: |
          🚨 Alerta DevOps Lab

          Alerta:
          {{ .GroupLabels.alertname }}

          Estado:
          {{ .Status }}
