---
- name: Generar configuracion Alertmanager
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ playbook_dir }}/../monitoring/alertmanager/alertmanager.yml"
    mode: "0644"
  delegate_to: localhost
  become: false
