---
- name: Configuracion base de servidores
  hosts: servers
  become: true

  tasks:
    - name: Actualizar cache apt
      apt:
        update_cache: yes

    - name: Actualizar paquetes instalados
      apt:
        upgrade: dist

    - name: Instalar herramientas base
      apt:
        name:
          - curl
          - wget
          - vim
          - nano
          - htop
          - net-tools
          - iputils-ping
          - unzip
          - git
        state: present
    
    - name: Crear directorio de proyectos
      file:
        path: /opt/projects
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Mostrar hostname
      debug:
        msg: "Servidor congigurado: {{ inventory_hostname }}"

