---
- name: Instalar Nginx en todos los servidores
  hosts: servers
  become: true

  tasks:
    - name: Actualizar cache de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes base
      apt:
        name: 
          - nginx
          - curl
          - vim
          - htop
        state: present